global:
  scrape_interval:     15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['172.28.0.6:8000']  # Replace with the address where your Go application is running

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.28.1.4:9100']  # Replace with the address where your Go application is running

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['172.28.1.3:8080']  # Replace with the address where your Go application is running
